spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: <copy-client-id-from-github>
            clientSecret: <copy-client-secret-from-github-oauth-app>
            redirectUri: http://localhost:4200/callback

